# Generated by Django 4.1.4 on 2023-01-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='usernam',
            new_name='username',
        ),
    ]
